// This file is auto-generated by the fetchThumbnails.js script
// It contains article data with thumbnails fetched from the LinkPreview API

// Default empty data that will be replaced by the script
const articlesWithThumbnails = [];

export { articlesWithThumbnails };
